name: Workflow Name
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Translate issue body
        uses: actions-gh-release-translate@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lock threads
        uses: dessant/lock-threads@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
